### ISSUE TITLE
request: set jfxr.autoplay to false onload

### ISSUE THREAD

**Issue by blurymind** [ttencate/jfxr#37]
this is so the app doesnt autoplay upon loading.
I am trying to stop it from playing a sound when loading , because when embeding it in gdevelop, I am making it load a sound that it previously stored in a gdevelop project- after it has loaded.

What ends up happening is that it loads, it plays the last edited sound from another resource, then loads the sound from my resource and plays it after.

I was wondering if there is a way of disabling this by appending autoplay=0 to the url of the app or something

**Comment by ttencate** [comment]
Can you access `localStorage` before the app is fully loaded? If so, it should work if you do `localStorage['autoplayEnabled'] = 'false'`.

**Comment by blurymind** [comment]
Hi I will try :)
Before I gain access to jsfx controller, I have to wait for it to load inside the iframe

You can see it here:

My request here was for a way to disable the autoplay by appending something to the url, like
`.../index.html#autoplay=0`

That will make it so much easier

**Comment by ttencate** [comment]
I think the autoplay on load was just a side effect of how Angular initializes its watches, and not necessarily a feature I included on purpose. In any case it will stop working in newer Chrome versions soon, because sites will require user interaction before they are allowed to play any audio. So I'll just suppress the autoplay on load altogether.

**Comment by blurymind** [comment]
Thank you 😸 
This will allow me to remove the half broken workaround I had with muting the electron window and unmuting it
